### ISSUE TITLE
Error while executing atom: [object Object]

### ISSUE THREAD

**Issue by shapovalovei** [google/ios-webkit-debug-proxy#205]
Hi all, I use appium for run test on mobile browser. Appium use ios-webkit-debug-proxy. Sometimes I have strange error "Error while executing atom: [object Object]". I think  ios-webkit-debug-proxy send incorrect answer 

```
[HTTP] --> POST /wd/hub/session/901c2751-c3b6-40c8-bf2d-2ac57be8c0e2/elements {"using":"xpath","value":"//div[@class='mw-note-value' and text()='8536675 ']"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["xpath","//div[@class='mw-note-value' and text()='8536675 ']","901c2751-c3b6-40c8-bf2d-2ac57be8c0e2"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 30000 ms for condition
[debug] [RemoteDebugger] Executing 'find_elements' atom in default context
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var aa="function"...
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate...
[debug] [RemoteDebugger] Receiving WebKit data: {"result":{"result":{"type"...
[debug] [RemoteDebugger] Found handler for message '20'
[MJSONWP] Encountered internal error running command: Error: Error while executing atom: [object Object]
    at XCUITestDriver.callee$0$0$ (../../../lib/commands/web.js:78:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session/901c2751-c3b6-40c8-bf2d-2ac57be8c0e2/elements 500 3235 ms - 214 
May 16, 2017 2:46:29 PM org.openqa.selenium.support.ui.ExpectedConditions findElement
WARNING: WebDriverException thrown by findElement(By.xpath: //div[@class='mw-note-value' and text()='8536675 '])
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error while executing atom: [object Object] (WARNING: The server did not provide any stacktrace information)
```

![screen shot 2017-05-17 at 5 56 50 pm](https://cloud.githubusercontent.com/assets/8914951/26161273/2900dbdc-3b2c-11e7-9e0b-aed38c261e96.png)
![Uploading Screen Shot 2017-05-17 at 17.43.50.png…]()

Can you help me ?

**Comment by shapovalovei** [comment]
One screenshot is missing. On this screenshot, I don't see any tags 
<img width="1873" alt="screen shot 2017-05-17 at 17 43 50" src="https://cloud.githubusercontent.com/assets/8914951/26219881/4d7ef8c0-3c19-11e7-9a45-97c1d811f857.png">

**Comment by artygus** [comment]
hi @shapovalovei, I'm not sure why you get "Error while executing atom.." error, I'm not familiar with appium. But you see objects instead of class names in dev tools because 

> in recent versions of Chrome and Safari there're major discrepancies between Chrome Remote Debugging Protocol and Apple's Remote Web Inspector service, which means that newer versions of Chrome DevTools arne't compatible with Safari.

see https://github.com/google/ios-webkit-debug-proxy#using-with-devtools section for more information

**Comment by shapovalovei** [comment]
Thanks, we can close Issues its a problem with special charters
