### ISSUE TITLE
Getting an error when trying to execute iOS native app(xcode 9.1 , appium 1.7.0 ,iOS 11.0)

### ISSUE THREAD

**Issue by lahiruw** [google/ios-webkit-debug-proxy#232]
Any idea why this fails ?

Log as below
---------------
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1508903131122 (09:15:31 GMT+0530 (+0530))
[Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver (v2.49.0) session
[Appium] Capabilities:
[Appium]   noReset: false
[Appium]   bundleId: 'com.abc.orderingqa'
[Appium]   autoDismissAlerts: true
[Appium]   xcodeConfigFile: '/Users/admin/IdeaProjects/QA-abc-Classic-Mobile/src/main/resources/Config.xcconfig'
[Appium]   startIWDP: true
[Appium]   deviceName: 'iOS'
[Appium]   newCommandTimeout: 3000
[Appium]   platformVersion: '11.0'
[Appium]   automationName: 'Appium'
[Appium]   autoWebview: true
[Appium]   udid: '123'
[Appium]   platformName: 'iOS'
[XCUITest] The capabilities 'autoAcceptAlerts' and 'autoDismissAlerts' do not work for XCUITest-based tests. Please adjust your alert handling accordingly.
[BaseDriver] Session created with session id: fa200d69-0de9-473e-b788-66f7243400f1
[debug] [XCUITest] Xcode version set to '9.1' (tools v9.0.1.0.1.1506734476)
[debug] [XCUITest] iOS SDK Version set to '11.1'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1508903131416 (09:15:31 GMT+0530 (+0530))
[debug] [XCUITest] Available devices: 123
[debug] [XCUITest] Creating iDevice object with udid '123'
[XCUITest] Determining device to run tests on: udid: '123', real device: true
[debug] [BaseDriver] Event 'appConfigured' logged at 1508903131586 (09:15:31 GMT+0530 (+0530))
[debug] [BaseDriver] Event 'resetStarted' logged at 1508903131587 (09:15:31 GMT+0530 (+0530))
[debug] [XCUITest] Reset: running ios real device reset flow
[debug] [BaseDriver] Event 'resetComplete' logged at 1508903131587 (09:15:31 GMT+0530 (+0530))
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Starting iOS device log capture with: 'idevicesyslog'
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1508903131613 (09:15:31 GMT+0530 (+0530))
[XCUITest] Setting up real device
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[debug] [XCUITest] Capability 'useNewWDA' set to false, so trying to reuse currently running WDA instance at 'http://localhost:8100/'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] WDA is not listening at 'http://localhost:8100/'. Rebuilding...
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1508903131992 (09:15:31 GMT+0530 (+0530))
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing running processes 'xcodebuild.*123, iproxy 8100' for the device 123...
[debug] [XCUITest] 'pgrep -nif xcodebuild.*123' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] 'pgrep -nif iproxy 8100' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [XCUITest] Using Xcode 9.1, so fixing WDA codebase
[debug] [XCUITest] Using Xcode configuration file: '/Users/admin/IdeaProjects/QA-Sysco-Classic-Mobile/src/main/resources/Config.xcconfig'
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=123 IPHONEOS_DEPLOYMENT_TARGET=11.0 -xcconfig /Users/admin/IdeaProjects/QA-Sysco-Classic-Mobile/src/main/resources/Config.xcconfig' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged. To see xcode logging, use 'showXcodeLog' desired capability
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Log file for xcodebuild test: /var/folders/9p/0x319fwj4gl9cbgcmjf7ycl00000gn/T/com.apple.dt.XCTest/IDETestRunSession-E16CB418-A610-4FDD-8FFF-C0B37BFF3A13/WebDriverAgentRunner-155B254D-6B59-4A1D-ADCD-F066C6CAE82A/Session-WebDriverAgentRunner-2017-10-25_091546-DtwF1d.log
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"11.0.1\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"11.0.1\",\n      \"ip\" : \"169.254.161.230\"\n    },\n    \"build\" : {\n      \"time\" : \"Oct 25 2017 09:15:41\"\n    }\n  },\n  \"sessionId\" : \"EB34F9FC-4529-456D-BC19-AEE00574830B\",\n  \"status\" : 0\n}"
[debug] [XCUITest] WebDriverAgent running on ip '169.254.161.230'
[debug] [XCUITest] WebDriverAgent successfully started after 17621ms
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1508903154862 (09:15:54 GMT+0530 (+0530))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.abc.orderingqa","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"sessionId":"025B721E-5616-4748-98E7-A4143BF837AB","capabilities":{"device":"iphone","browserName":"Ordering QA","sdkVersion":"11.0.1","CFBundleIdentifier":"com.abc.orderingqa"}},"sessionId":"025B721E-5616-4748-98E7-A4143BF837AB","status":0}
[debug] [BaseDriver] Event 'wdaSessionStarted' logged at 1508903157217 (09:15:57 GMT+0530 (+0530))
[debug] [XCUITest] Cannot find a match for DerivedData folder path from lsof. Trying to access logs
[XCUITest] Setting '555' permissions to '/Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Attachments' folder
[debug] [BaseDriver] Event 'wdaPermsAdjusted' logged at 1508903157272 (09:15:57 GMT+0530 (+0530))
[debug] [BaseDriver] Event 'wdaStarted' logged at 1508903157273 (09:15:57 GMT+0530 (+0530))
[debug] [XCUITest] Setting initial orientation to 'PORTRAIT'
[debug] [JSONWP Proxy] Proxying [POST /orientation] to [POST http://localhost:8100/session/025B721E-5616-4748-98E7-A4143BF837AB/orientation] with body: {"orientation":"PORTRAIT"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"Unable To Rotate Device","sessionId":"025B721E-5616-4748-98E7-A4143BF837AB","status":777}
[XCUITest] Setting initial orientation failed with: UnknownError: An unknown server-side error occurred while processing the command. Original error: Unable To Rotate Device
[debug] [BaseDriver] Event 'orientationSet' logged at 1508903163584 (09:16:03 GMT+0530 (+0530))
[debug] [BaseDriver] Event 'iwdpStarting' logged at 1508903163585 (09:16:03 GMT+0530 (+0530))
[debug] [iOS] Starting ios_webkit_debug_proxy at port 27753 on device 123
[IWDP] [ 'Could not connect to lockdownd. Exiting.: Undefined error: 0' ]
[IWDP] [ 'Unable to attach 123 inspector' ]
[debug] [iOS] Starting ios_webkit_debug_proxy at port 27753 on device 123
[iOS] Error: Timed out waiting for ios_webkit_debug_proxy to open
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at IWDP.start$ (../../lib/iwdp.js:61:14)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
 Error: Timed out waiting for ios_webkit_debug_proxy to open
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at IWDP.start$ (../../lib/iwdp.js:61:14)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
[XCUITest] Error: Could not start ios_webkit_debug_proxy server: Timed out waiting for ios_webkit_debug_proxy to open
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at XCUITestDriver.start$ (../../lib/driver.js:328:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
 Error: Could not start ios_webkit_debug_proxy server: Timed out waiting for ios_webkit_debug_proxy to open
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at XCUITestDriver.start$ (../../lib/driver.js:328:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
[XCUITest] Error: Could not start ios_webkit_debug_proxy server: Timed out waiting for ios_webkit_debug_proxy to open
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at XCUITestDriver.start$ (../../lib/driver.js:328:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
 Error: Could not start ios_webkit_debug_proxy server: Timed out waiting for ios_webkit_debug_proxy to open
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at XCUITestDriver.start$ (../../lib/driver.js:328:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
[debug] [JSONWP Proxy] Proxying [DELETE /session/fa200d69-0de9-473e-b788-66f7243400f1] to [DELETE http://localhost:8100/session/025B721E-5616-4748-98E7-A4143BF837AB] with no body
[IWDP] [ 'Could not connect to lockdownd. Exiting.: Undefined error: 0' ]
[IWDP] [ 'Unable to attach 123 inspector' ]
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n\n  },\n  \"sessionId\" : \"3E0703D6-E12F-46A2-942B-75DD97A53BAD\",\n  \"status\" : 0\n}"
[XCUITest] Setting '755' permissions to '/Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Attachments' folder
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Could not start ios_webkit_debug_proxy server: Timed out waiting for ios_webkit_debug_proxy to open
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at XCUITestDriver.start$ (../../lib/driver.js:328:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
[HTTP] <-- POST /wd/hub/session 500 43028 ms - 236 
[iOS] Error: Timed out waiting for ios_webkit_debug_proxy to open
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at IWDP.start$ (../../lib/iwdp.js:61:14)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
 Error: Timed out waiting for ios_webkit_debug_proxy to open
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at IWDP.start$ (../../lib/iwdp.js:61:14)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
(node:2000) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: Timed out waiting for ios_webkit_debug_proxy to open
(node:2000) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[debug] [XCUITest] Connection to WDA timed out
[debug] [iProxy] recv failed: Operation not permitted
ndled promise rejection (rejection id: 4): Error: Timed out waiting for ios_webkit_debug_proxy to open
(node:2000) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[debug] [XCUITest] Connection to WDA timed out
[debug] [iProxy] recv failed: Operation not permitted

**Comment by artygus** [comment]
hi @lahiruw, what does output of `ios_webkit_debug_proxy -V` show? you probably need to build libimimobiledevice from master branch, if you're on OS X you could try 

    brew update
    brew reinstall --HEAD libimobiledevice
    brew reinstall -s ios-webkit-debug-proxy

**Comment by lahiruw** [comment]
@artygus Thanks for the reply 
results for -v shows,
ios_webkit_debug_proxy 1.8
Built with libimobiledevice v1.2.1, libplist v2.0.0

i took libimimobiledevice from master few times .

**Comment by artygus** [comment]
hm.. it says, 

> Could not connect to lockdownd. Exiting.: Undefined error: 0

did you try to remove your device from lockdown directory? it should be /var/db/lockdown, and what  permissions set on the lockdown dir?

**Comment by lahiruw** [comment]
@artygus Tries with the solution you provided .cleared lockdown directory and retried .
`[iOS] Error: Timed out waiting for ios_webkit_debug_proxy to open
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at IWDP.start$ (../../lib/iwdp.js:61:14)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
 Error: Timed out waiting for ios_webkit_debug_proxy to open
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at IWDP.start$ (../../lib/iwdp.js:61:14)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
[XCUITest] Error: Could not start ios_webkit_debug_proxy server: Timed out waiting for ios_webkit_debug_proxy to open
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at XCUITestDriver.start$ (../../lib/driver.js:336:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
 Error: Could not start ios_webkit_debug_proxy server: Timed out waiting for ios_webkit_debug_proxy to open
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at XCUITestDriver.start$ (../../lib/driver.js:336:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
[XCUITest] Error: Could not start ios_webkit_debug_proxy server: Timed out waiting for ios_webkit_debug_proxy to open
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at XCUITestDriver.start$ (../../lib/driver.js:336:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
 Error: Could not start ios_webkit_debug_proxy server: Timed out waiting for ios_webkit_debug_proxy to open
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at XCUITestDriver.start$ (../../lib/driver.js:336:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
[debug] [JSONWP Proxy] Proxying [DELETE /session/91c67394-eb46-4a4b-b188-7b0de08d999c] to [DELETE http://localhost:8100/session/8DB2DB97-F907-4FB3-847A-E1EF8EE1BEF7] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n\n  },\n  \"sessionId\" : \"B7D94A8E-F993-4B27-890D-AAC23B618FDC\",\n  \"status\" : 0\n}"
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down xcodebuild process (pid 30853)
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGTERM'
[XCUITest] Shutting down iproxy process (pid 30852)
[debug] [XCUITest] iproxy exited with code 'null'
[debug] [XCUITest] Found WDA derived data folder: '/Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy'
[XCUITest] Setting '755' permissions to '/Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Attachments' folder
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Could not start ios_webkit_debug_proxy server: Timed out waiting for ios_webkit_debug_proxy to open
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at XCUITestDriver.start$ (../../lib/driver.js:336:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
`

**Comment by artygus** [comment]
ehm.. could you please try running `ios-webkit-debug-proxy -d` from console (with connected device)

**Comment by lahiruw** [comment]
@artygus ohhh the issue was web view is disabled ...Thanks a Loooooootttttttt !

Below comment is for any one who looks this issue .
*i was able to execute native application with xcode9/appium 1.6 or later and iOS11.1 .

**Comment by klingham** [comment]
@lahiruw How did you enable the webview if it was disabled? I'm getting this same error as the title of the issue and unable to proceed further.
