### ISSUE TITLE
segmentation fault in SSL_write

### ISSUE THREAD

**Issue by mozfreddyb** [google/ios-webkit-debug-proxy#360]
```
ios_webkit_debug_proxy --debug 
ss.add_server_fd(3)
Listing devices on :9221
ss.add_fd(4)
ss.add_server_fd(5)
ss.remove_server_fd(5)
ss.recv fd=4 len=959
ss.add_server_fd(5)
ss.add_fd(7)
wi.send_packet[198]:
 00 00 00 C2 62 70 6C 69 73 74 30 30 D2 01 03 02 04 5A 5F  ....bplist00.....Z_
 5F 73 65 6C 65 63 74 6F 72 5F 10 16 5F 72 70 63 5F 72 65  _selector_.._rpc_re
 70 6F 72 74 49 64 65 6E 74 69 66 69 65 72 3A 5A 5F 5F 61  portIdentifier:Z__a
 72 67 75 6D 65 6E 74 D1 05 06 5F 10 1A 57 49 52 43 6F 6E  rgument..._..WIRCon
 6E 65 63 74 69 6F 6E 49 64 65 6E 74 69 66 69 65 72 4B 65  nectionIdentifierKe
 79 5F 10 3C 32 33 30 35 31 65 65 65 37 31 37 66 32 62 ZZ  y_.<23051eee717f2bz
(cutting out some ID information, just in case the connection identifier contains personal info)
 36 2D 31 32 31 35 37 64 66 35 31 34 38 35 62 33 37 35 33  6-12157zz51485b3753
 37 32 62 66 30 36 66 08 0D 18 31 3C 3F 5C 00 00 00 00 00  72bf06f...1<?\.....
 00 01 01 00 00 00 00 00 00 00 07 00 00 00 00 00 00 00 00  ...................
 00 00 00 00 00 00 00 9B                                   ........
[1]    88965 segmentation fault (core dumped)  ios_webkit_debug_proxy --debug

```

Runnign with gdb gives me this backtrace:
```
#0  0x00007ffff7f18cb6 in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.1
#1  0x00007ffff7f18df7 in SSL_write () from /lib/x86_64-linux-gnu/libssl.so.1.1
#2  0x000055555556336e in sm_send (self=0x555555595770, fd=0x7, data=0x5555555b7900 "", 
    length=0xc5, value=0x0) at socket_manager.c:411
#3  0x000055555555a2cc in iwdp_send_packet (wi=<optimized out>, packet=<optimized out>, length=0xc5)
    at ios_webkit_debug_proxy.c:1156
#4  0x000055555556383d in wi_send_plist (self=0x5555555a3300, rpc_dict=<optimized out>)
    at webinspector.c:357
#5  0x000055555555e568 in rpc_send_msg (self=self@entry=0x5555555abef0, 
    selector=selector@entry=0x555555568cb6 "_rpc_reportIdentifier:", args=args@entry=0x5555555a3650)
    at rpc.c:118
#6  0x000055555555ebd2 in rpc_send_msg (args=0x5555555a3650, 
    selector=0x555555568cb6 "_rpc_reportIdentifier:", self=0x5555555abef0) at rpc.c:136
#7  rpc_send_reportIdentifier (connection_id=<optimized out>, self=0x5555555abef0) at rpc.c:134
#8  rpc_send_reportIdentifier (self=0x5555555abef0, connection_id=<optimized out>) at rpc.c:128
#9  0x000055555555c26f in iwdp_on_attach (dl=<optimized out>, device_id=<optimized out>, 
    device_num=<optimized out>) at ios_webkit_debug_proxy.c:450
#10 0x0000555555559928 in dl_recv_packet (self=self@entry=0x555555598790, 
    packet=packet@entry=0x55555558d886 "\231\002", length=<optimized out>) at device_listener.c:262
#11 0x00005555555599e5 in dl_recv_loop (self=self@entry=0x555555598790) at device_listener.c:298
#12 0x0000555555559ac0 in dl_on_recv (self=0x555555598790, buf=<optimized out>, 
    length=<optimized out>) at device_listener.c:325
#13 0x0000555555562ba0 in sm_recv (self=self@entry=0x555555595770, fd=fd@entry=0x4)
    at socket_manager.c:607
#14 0x0000555555562ec5 in sm_select (self=0x555555595770, timeout_secs=<optimized out>)
    at socket_manager.c:673
#15 0x0000555555557cfb in main (argc=argc@entry=0x2, argv=argv@entry=0x7fffffffdf28)
    at ios_webkit_debug_proxy_main.c:94
#16 0x00007ffff7ba30b3 in __libc_start_main (main=0x555555557c80 <main>, argc=0x2, 
    argv=0x7fffffffdf28, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffdf18) at ../csu/libc-start.c:308
#17 0x0000555555557d6e in _start () at ios_webkit_debug_proxy_main.c:81
```

**Comment by nhardy** [comment]
I had the same issue, but following the instructions in this comment resolved the issue: https://github.com/google/ios-webkit-debug-proxy/issues/331#issuecomment-619459289

**Comment by mozfreddyb** [comment]
Yes, indeed. Thank you @nhardy. Closing this one.
